language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t salamatburj/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true salamatburj/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "southeast-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-674224916912"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY 

  
